# Generated by Django 2.1.15 on 2020-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student_roll_number',
            field=models.IntegerField(),
        ),
    ]
